image: docker:latest
services:
  - name: docker:dind
    alias: docker

variables:
  DO_TOKEN: $DO_TOKEN
  APP_NAME: "portfolio"
  DOCKER_TLS_CERTDIR: ""
  DO_REGISTRY: "amir734jj"
  DOCKER_HOST: "tcp://docker:2375"
  HEROKU_REGISTRY: "registry.heroku.com"
  HEROKU_EMAIL: "hesamian@uwm.edu"

stages:
  - deploy

docker-build:
  stage: deploy
  resource_group: heroku
  only:
    - master
  allow_failure: false
  before_script:
    - apk update
    - apk --no-cache add curl
    - curl -Lo doctl.tar.gz https://github.com/digitalocean/doctl/releases/download/v1.100.0/doctl-1.100.0-linux-amd64.tar.gz && tar xf doctl.tar.gz
    - chmod u+x doctl
    - mv doctl /usr/local/bin/doctl
  script:
    - doctl auth init --access-token $DO_TOKEN
    - doctl registry login
    - docker build -t registry.digitalocean.com/$DO_REGISTRY/$APP_NAME .
    - docker push registry.digitalocean.com/$DO_REGISTRY/$APP_NAME